name: release

on: workflow_dispatch

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write ### make sure not use pull_requests instead of pull-requests
      
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: release
        run: npm install --save-dev semantic-release
        
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          